version: '3.8'

services:
  flask:
    build: .
    container_name: cloudguard-api
    environment:
      - FINDINGS_TABLE=cloudguard-findings
      - AWS_DEFAULT_REGION=ap-south-1
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - cloudguard-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
    - cloudguard-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - cloudguard-network

networks:
  cloudguard-network:
    driver: bridge
